[package]
name = "hi-wo"
version = "0.1.0"
edition = "2018"

# [dependencies]
# wry = "0.11"

[dev-dependencies]
xargo = "*"

[profile.dev]
panic = "abort"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
